services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
      POSTGRES_DB:       dancecrm
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet

  web:
    build:
      context: dancecrm-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certs:/etc/nginx/certs:ro
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
