# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /app

# Установим зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код
COPY . .

# Переменные окружения (можно вынести в .env)
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=production

# Открываем порт
EXPOSE 5000

# Запуск
CMD ["flask", "run"]