"""Rename metadata → extra_data in ClassInstance

Revision ID: 0d6c2074b9d0
Revises: f67a5114cd59
Create Date: 2025-05-10 23:58:17.331044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6c2074b9d0'
down_revision = 'f67a5114cd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recurring_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('cancelled_dates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['class_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['recurring_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_instance')
    op.drop_table('recurring_schedule')
    op.drop_table('class_type')
    # ### end Alembic commands ###
