"""Add start_date to RecurringSchedule

Revision ID: 2fcbb9bfbba0
Revises: f960f60dbc72
Create Date: 2025-05-11 15:42:19.293408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcbb9bfbba0'
down_revision = 'f960f60dbc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_schedule', schema=None) as batch_op:
        # Добавляем колонку со временным default, чтобы заполнить все старые записи
        batch_op.add_column(
            sa.Column(
                'start_date',
                sa.Date(),
                nullable=False,
                server_default=sa.text('CURRENT_DATE')
            )
        )
        # Сразу снимаем серверный default, чтобы дальше INSERT требовал явный start_date
        batch_op.alter_column(
            'start_date',
            server_default=None
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_schedule', schema=None) as batch_op:
        batch_op.drop_column('start_date')
    # ### end Alembic commands ###
